/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alqueit (https://sketchfab.com/Alqueit)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/genshin-impact-ayaka-8d5e1de3fc8941278f96776cceff0d92
title: Genshin Impact: Ayaka
*/

import * as THREE from 'three';
import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.SkinnedMesh;
    Object_10: THREE.SkinnedMesh;
    Object_12: THREE.SkinnedMesh;
    Object_13: THREE.SkinnedMesh;
    Object_14: THREE.SkinnedMesh;
    Object_16: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    Avatar_Girl_Sword_Ayaka_Mat_Face: THREE.MeshStandardMaterial;
    Avatar_Girl_Sword_Ayaka_Mat_Hair: THREE.MeshStandardMaterial;
    Avatar_Girl_Sword_Ayaka_Mat_Body: THREE.MeshStandardMaterial;
    Avatar_Girl_Sword_Ayaka_Mat_Dress: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF('/ayaka.gltf') as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={2}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_8.geometry}
            material={materials.Avatar_Girl_Sword_Ayaka_Mat_Face}
            skeleton={nodes.Object_8.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_10.geometry}
            material={materials.Avatar_Girl_Sword_Ayaka_Mat_Face}
            skeleton={nodes.Object_10.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_12.geometry}
            material={materials.Avatar_Girl_Sword_Ayaka_Mat_Hair}
            skeleton={nodes.Object_12.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_13.geometry}
            material={materials.Avatar_Girl_Sword_Ayaka_Mat_Body}
            skeleton={nodes.Object_13.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_14.geometry}
            material={materials.Avatar_Girl_Sword_Ayaka_Mat_Dress}
            skeleton={nodes.Object_14.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_16.geometry}
            material={materials.Avatar_Girl_Sword_Ayaka_Mat_Face}
            skeleton={nodes.Object_16.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/ayaka.gltf');
